version: '3.3'

services:
  my_database:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=bienesraices_node_mvc
      - MYSQL_USER=
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
 
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    hostname: my_database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80